### ISSUE TITLE
add per capita QALY loss to the QALY map

### ISSUE THREAD

**Issue by aminadibi** [resplab/burden_of_asthma_in_US#5]
QALY map only shows total sum of QALY sum. Provide a radio button option of "per capita QALY" and make it default view. Also, please double check to make sure numbers agree with the published prepring
[https://www.biorxiv.org/content/biorxiv/early/2019/01/12/516740.full.pdf](https://www.biorxiv.org/content/biorxiv/early/2019/01/12/516740.full.pdf)

**Comment by aminadibi** [comment]
@ahill187 Mohsen was following up on this. Any updates?

**Comment by ahill187** [comment]
https://github.com/resplab/burden_of_asthma_in_US/pull/31
