### ISSUE TITLE
Graph produces weird outcome when X-axis is "year"

### ISSUE THREAD

**Issue by aminadibi** [resplab/burden_of_asthma_in_US#7]
![bug](https://user-images.githubusercontent.com/20497354/56054003-7970c300-5d0a-11e9-93b9-5a74ecd2075d.PNG)

What is this? Could you please fix, and test that no other combination results in this bug?

**Comment by ahill187** [comment]
closed in https://github.com/resplab/burden_of_asthma_in_US/commit/1dcd9edac3934a53c91df7cc1991a88b3a47e23c
